name: dotnet package

on: [push]

jobs:
  build:

    runs-on: self-hosted    
#    strategy:
#      matrix:
#        dotnet-version: ['3.0', '3.1.x', '5.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 3.1
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.x
      - name: Setup .NET SDK 5.0
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal --configuration Release
      - name: Pack
        run: dotnet pack --no-build --verbosity normal --configuration Release
